apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-small-workload
  labels:
    app: {{ .Release.Name }}-small-workload
spec:
  selector:
    app: {{ .Release.Name }}-small-workload
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8080
